version: '3.1'

services:
  wordpress:
    image: wordpress:php8.1
    ports:
      - 12080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/isrp-event-paygate

  db:
    image: mariadb:latest
    ports:
      - 12306:3306
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  wpcli:
    container_name: cli
    depends_on:
      - wordpress
    image: wordpress:cli-php8.1
    user: 0:0
    volumes:
      - wordpress:/var/www/html
      - .:/var/www/html/wp-content/plugins/isrp-event-paygate
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wordpress
    profiles:
      - dev

volumes:
  wordpress:
  db:
